### ISSUE TITLE
Problem :  Sourcery in Vscode desktop , Project disabled for account

### ISSUE THREAD

**Issue by zakimimit** [sourcery-ai/sourcery#402]
I  can't use sourcery in desktop  with Vscode
I used to work with sourcery on my desktop  without any prroblem
I Work on my local machine

Error: Your Open Source Sourcery account can't be used for private projects.

![image](https://github.com/sourcery-ai/sourcery/assets/46423256/ae3ce1df-9750-4d19-825c-7a815e052941)

**Comment by bm424** [comment]
Hi @zakimimit, thanks for bringing this to our attention. We noticed a data integrity issue with your account in our database, which I've now fixed. Please let us know if you are now able to use Sourcery. If not, please send an email to support@sourcery.ai, with your sourcery log file (documentation [here](https://docs.sourcery.ai/Product/Troubleshooting/#what-is-the-sourcery-log)) attached, and we'll try to debug the problem. I'm going to close this GitHub issue.

**Comment by aonomike** [comment]
hi @bm424 I am having the same issue as this, could this be a data integrity issue on my side as well?

**Comment by zakimimit** [comment]
I still have ths issue , nothing fixed , is there any things I can do  ?

**Comment by zakimimit** [comment]
> Hi @zakimimit, thanks for bringing this to our attention. We noticed a data integrity issue with your account in our database, which I've now fixed. Please let us know if you are now able to use Sourcery. If not, please send an email to [support@sourcery.ai](mailto:support@sourcery.ai), with your sourcery log file (documentation [here](https://docs.sourcery.ai/Product/Troubleshooting/#what-is-the-sourcery-log)) attached, and we'll try to debug the problem. I'm going to close this GitHub issue.



I still have this issue , nothing fixed , are there any things I can do  ?

**Comment by simplylu** [comment]
Experiencing the same issue.
